//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA
    {
        public string MaKetQua { get; set; }
        public string MaHocVien { get; set; }
        public Nullable<int> LoaiKetQua { get; set; }
        public string Diem { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual HOCVIEN HOCVIEN { get; set; }
    }
}
