//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPHOC
    {
        public string MaLopHoc { get; set; }
        public int Muc { get; set; }
        public string TenLopHoc { get; set; }
        public decimal HocPhi { get; set; }
        public string BuoiHoc { get; set; }
        public System.TimeSpan GioBatDau { get; set; }
        public System.TimeSpan GioKetThuc { get; set; }
        public int TrangThai { get; set; }
    
        public virtual GIAOVIEN_LOPHOC GIAOVIEN_LOPHOC { get; set; }
        public virtual HOCVIEN_LOPHOC HOCVIEN_LOPHOC { get; set; }
        public virtual LOPHOC_KHOAHOC LOPHOC_KHOAHOC { get; set; }
    }
}
